# Twitch Stream Monitor Configuration
# Copy this file and customize it for your setup

# Twitch API Configuration
# Get your credentials from https://dev.twitch.tv/console/apps
twitch:
  client_id: "your_twitch_client_id_here"
  client_secret: "your_twitch_client_secret_here"

# ntfy.sh Notification Configuration
ntfy:
  # The ntfy.sh topic to send notifications to
  # Choose something unique and hard to guess
  topic: "your_unique_topic_here"
  
  # ntfy.sh server (default: https://ntfy.sh)
  # You can use your own self-hosted ntfy server
  server: "https://ntfy.sh"
  
  # Notification priority (1-5, or min/low/default/high/max)
  priority: "high"
  
  # Tags for the notification (comma-separated)
  tags: "twitch,live,streaming"
  
  # Whether to include a click URL to the stream
  click_url: true
  
  # Custom icon URL (optional)
  # icon: "https://example.com/twitch-icon.png"
  
  # Request timeout in seconds
  timeout: 10

# List of Twitch usernames to monitor
# Add the streamers you want to get notifications for
streamers:
  - "example_streamer_1"
  - "example_streamer_2"
  # Add more streamers here

# Monitoring Configuration
# How often to check for stream status (in seconds)
# Recommended: 60-300 seconds to respect API rate limits
poll_interval: 120

# Maximum number of retries on API failures
max_retries: 3

# Delay between retries (in seconds)
retry_delay: 60

# File to store stream state for deduplication
state_file: "stream_state.json"

# Notification message template
# Available variables: {username}, {title}, {game}, {url}, {started_at}
message_template: |
  {username} is now live! 🎮
  
  📺 {title}
  🎮 Playing: {game}
  🕐 Started at: {started_at}
  
  Watch now: {url}

# Logging Configuration (optional)
# Uncomment and modify as needed
# logging:
#   level: "INFO"  # DEBUG, INFO, WARNING, ERROR
#   file: "twitch_monitor.log"
